services:
  db:
    restart: unless-stopped
    image: postgres:14
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
      - ./.docker/db_socket:/var/run/postgresql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    user: '1000:1001'
  app:
    build: .
    volumes:
      - ./:/app
      - ./.docker/logs:/app/logs
    depends_on:
      - db
    env_file: .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    command: ['sh', '-c', './node_modules/.bin/prisma migrate deploy && yarn dev']
