const [, , version, releaseName] = Bun.argv

if (!version || !releaseName) {
  console.error('usage: buildinfo.ts <version> <releaseName>')
  process.exit(1)
}

const file = `\
// NOTE: this file is generated by scripts/buildinfo.ts. Do not edit it directly!

export const GAMERBOT_VERSION = '${version}'
export const RELEASE_NAME = '${releaseName}'
`

Bun.write(Bun.file('lib/buildinfo.ts'), file)
